### PR TITLE
Correct code editing

### PR DESCRIPTION
**Pull request by Julia-Lavrova**
If you entered an invalid code and want to correct it in the center, not with the last letter, I have a problem. The code render isn't correct. Example:
first input: `1234`
after that, I want to change '23' in code 
`1_ _4`
and input new second letter '8'. 
Expected Result: 
`18_4`, 
but real result: 
`1844` 
and output value "184". The same situation was if I correct the third letter.  

Please, @40818419, see the request, and merge it, if everything ok.

### CODE REVIEW

**Comment by Julia-Lavrova** [comment]
@40818419 I updated the PR, please, merge it, if everything is ok. 
I want to use [jest ](https://facebook.github.io/jest/) for testing. If you do not mind, I will make a request and re-write your tests. :)

**Comment by 40818419** [comment]
LGTM Julia, thanx a ton! Feel free to migrate to jest. here is the issue for that: #25

**Comment by Julia-Lavrova** [comment]
It's great! Thank you!

**Comment by Julia-Lavrova** [comment]
Please, make a release with updates :)

**Comment by 40818419** [comment]
@Julia-Lavrova done

**Pull request merged**
